### ISSUE TITLE
debouncer not working

### ISSUE THREAD

**Issue by cquiroz** [gemini-hlsw/explore#1484]
I was expecting debouncer to accumulate events and only fire at most once per the defined time
Instead it seems to be delaying the call and only firing once a sec but accumulating all hits

This code:
```
        panels.zoom(treeWidthLens).set(d.size.width) *>
          debouncer
            .submit(
              IO.println(s"pane ${d.size.width}") *>
                UserWidthsCreation
                  .storeWidthPreference[IO](props.userId,
                                            ResizableSection.TargetsTree,
                                            d.size.width
                  )
            )
            .runAsyncAndForget
```
prints the pane slowly instead of only once or twice as I expected

**Comment by rpiaggio** [comment]
Thanks for reporting, there was a bug in crystal.

Addressed in https://github.com/rpiaggio/crystal/pull/328
